# Generated by Django 5.1.5 on 2025-02-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
